fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: trailing-whitespace
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.259'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: local-mypy
        name: local-mypy
        entry: mypy cblit/
        language: system
        types: [python]
        pass_filenames: false
